# Generated by Django 4.2.9 on 2024-05-08 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_update_on_article_updated_on_article_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='updated_on',
            new_name='update_on',
        ),
    ]
