# Generated by Django 4.2.9 on 2024-05-06 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_author_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='update_on',
            new_name='updated_on',
        ),
    ]
