# Generated by Django 4.2.9 on 2024-05-08 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_updated_on_comment_update_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='update_on',
            new_name='updated_on',
        ),
    ]
