# Generated by Django 4.2.3 on 2024-05-08 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchstore', '0002_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_status',
            field=models.CharField(choices=[('IN CART', 'In Cart'), ('TO PAY', 'To Pay'), ('TO SHIP', 'To Ship'), ('TO RECEIVE', 'To Receive'), ('DELIVERED', 'Delivered')], default='IN CART', max_length=20),
        ),
    ]
